# Generated by Django 3.2 on 2021-04-09 19:38

import Users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_reports', models.TextField()),
                ('warned', models.BooleanField(default=False)),
                ('warn_description', models.TextField(blank=True)),
                ('warn_date', models.DateTimeField(default=Users.models.localtime)),
                ('banned', models.BooleanField(default=False)),
                ('ban_description', models.TextField(blank=True)),
                ('ban_date', models.DateTimeField(default=Users.models.localtime)),
                ('banned_by', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='banned_by', to=settings.AUTH_USER_MODEL)),
                ('banned_for', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='banned_for', to='Books.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('warned_by', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='warned_by', to=settings.AUTH_USER_MODEL)),
                ('warned_for', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='warned_for', to='Books.book')),
            ],
        ),
    ]
